import pandas as pd

df = pd.read_csv("ScrapingScripts/RawOutput/RisultatiComunali/COMUNALI.csv")

mapping_dict = {
    'DONATI GILBERTO\nCENTRO' : 'DONATI GILBERTO\n(CENTRO)', 
    "ROMANO' MARCO\nL.NORD-CIVICHE" : "ROMANO' MARCO\n(L.NORD-CIVICHE)",
    'VITALI MAURIZIO\nSINISTRA' : 'VITALI MAURIZIO\n(SINISTRA)', 
    'DONATI GILBERTO\nLISTA CIVICA' : 'DONATI GILBERTO\n(LISTA CIVICA)',  
    'TURCO ANTONIO\nLISTA CIVICA' : 'TURCO ANTONIO\n(LISTA CIVICA)',
    'GUALDONI GIAN BATTISTA\nLISTA CIVICA' : 'GUALDONI GIAN BATTISTA\n(LISTA CIVICA)',
    'VITALI TERESA\nLISTA CIVICA' : 'VITALI TERESA\n(LISTA CIVICA)',
    'GIUDICI ANGELA\nCEN-DES(CONTR.UFF.)' : 'GIUDICI ANGELA\n(CEN-DES)',
    'GUALDONI GIAN BATTISTA\nINSIEME PER GUALDONI SINDACO VANZAGHELLO' : 'GUALDONI GIAN BATTISTA\n(INSIEME PER VANZAGHELLO)',
    "GARASCIA EMILIO MARIO\nIL POPOLO DELLA LIBERTA'" : "GARASCIA EMILIO MARIO\n(IL POPOLO DELLA LIBERTA')",
    'VITALI TERESA\nTERESA VITALI SINDACO' : 'VITALI TERESA\n(TERESA VITALI SINDACO)',
    'RUDONI ALESSIO\nLEGA NORD' : 'RUDONI ALESSIO\n(LEGA NORD)',
    'GIANI LEOPOLDO ANGELO\nINSIEME PER VANZAGHELLO' : 'GIANI LEOPOLDO ANGELO\n(INSIEME PER VANZAGHELLO)',
    'VALLI ELENA\nLEGA NORD-BASTA €URO-CIVICA' : 'VALLI ELENA\n(L.NORD-BASTA EURO-CIVICA)',
    'GATTI ARCONTE\nLEGA SALVINI-RIACCENDIAMO VANZAGHELLO' : 'GATTI ARCONTE\n(LEGA SALVINI <br> RIACCENDIAMO VANZAGHELLO)',
    'GUALDONI GIAN BATTISTA\nINSIEME PER VANZAGHELLO' : 'GUALDONI GIAN BATTISTA\n(INSIEME PER VANZAGHELLO)',
    'GATTI ARCONTE\nCENTRODESTRA UNITO PER VANZAGHELLO - RIACCENDIAMO VANZAGHELLO' : 'GATTI ARCONTE\n(CENTRODESTRA UNITO <br> RIACCENDIAMO VANZAGHELLO)',
    'GIANI RINO\nINSIEME PER VANZAGHELLO' : 'GIANI RINO\n(INSIEME PER VANZAGHELLO)'
}

df['CANDIDATO_LISTA'] = df.CANDIDATO_LISTA.apply(lambda x: mapping_dict[x] if x in mapping_dict.keys() else x)

df.to_csv(
    "SHINY_INPUT_DATA/COMUNALI.csv",
    index=False
)